version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-docker
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - appnet

  vault:
    image: hashicorp/vault:latest
    container_name: vault-docker
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: my-root-token
    depends_on:
      - postgres
      - vault
    ports:
      - "8080:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
