version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-docker
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
