spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    # TBD: externalize configuration to some Vault or AWS SecretManager pull-based external configuration model is acceptable
    username: testuser
    password: testpass
