spring:
  application:
    name: card-service
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Liquibase manages schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  # @Async configuration
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 200
      thread-name-prefix: CardAsync-

scryfall:
  base-url: https://api.scryfall.com

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

feign:
  client:
    config:
      scryfall:
        retryer: "never" # Use Resilience4j retry mechanism instead

# Default, can be environment-specific overrides in application-{profile}.yaml
resilience4j:
  retry:
    instances:
      scryfall-api-retry:
        max-attempts: 3
        wait-duration: 2000ms
        retry-exceptions:
          - feign.RetryableException
        ignore-exceptions: [ ]
        exponential-backoff-multiplier: 2.0

  circuitbreaker:
    instances:
      scryfall-circuit-breaker:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50